name: Angular_CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: CkeckOut
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "22.1.0"
          
      - name: Instalar Dependencias
        run:  npm i
      
      - name: Build Application
        run:  npm run build:prod 
      
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          build_dir: dist/browser
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}

